// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MProject.Packet
{

public enum Tag : uint
{
  Create = 0,
  Test = 1,
};


}
