// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MProject.Packet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct FProtocol : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public FProtocol __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Tag { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public byte HashCode(int j) { return __p.bb.Get(__p.bb_pos + 4 + j * 1); }

  public static Offset<MProject.Packet.FProtocol> CreateFProtocol(FlatBufferBuilder builder, uint Tag, byte[] HashCode) {
    builder.Prep(4, 36);
    for (int _idx0 = 32; _idx0 > 0; _idx0--) {
      builder.PutByte(HashCode[_idx0-1]);
    }
    builder.PutUint(Tag);
    return new Offset<MProject.Packet.FProtocol>(builder.Offset);
  }
}


}
