// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PACKETTAG_MPROJECT_PACKET_H_
#define FLATBUFFERS_GENERATED_PACKETTAG_MPROJECT_PACKET_H_

#include "flatbuffers/flatbuffers.h"

namespace MProject {
namespace Packet {

enum Tag : uint32_t {
  Tag_Create = 0,
  Tag_Test = 1,
  Tag_MIN = Tag_Create,
  Tag_MAX = Tag_Test
};

inline const Tag (&EnumValuesTag())[2] {
  static const Tag values[] = {
    Tag_Create,
    Tag_Test
  };
  return values;
}

inline const char * const *EnumNamesTag() {
  static const char * const names[3] = {
    "Create",
    "Test",
    nullptr
  };
  return names;
}

inline const char *EnumNameTag(Tag e) {
  if (flatbuffers::IsOutRange(e, Tag_Create, Tag_Test)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTag()[index];
}

}  // namespace Packet
}  // namespace MProject

#endif  // FLATBUFFERS_GENERATED_PACKETTAG_MPROJECT_PACKET_H_
