// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_USER_MPROJECT_USER_H_
#define FLATBUFFERS_GENERATED_USER_MPROJECT_USER_H_

#include "flatbuffers/flatbuffers.h"

#endif  // FLATBUFFERS_GENERATED_USER_MPROJECT_USER_H_
