// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MOVEMENT_MPROJECT_MOVEMENT_H_
#define FLATBUFFERS_GENERATED_MOVEMENT_MPROJECT_MOVEMENT_H_

#include "flatbuffers/flatbuffers.h"

#include "Core_generated.h"

namespace MProject {
namespace Movement {

struct MovementPacket;
struct MovementPacketBuilder;

struct MovementPacket FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MovementPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  int32_t x() const {
    return GetField<int32_t>(VT_X, 0);
  }
  int32_t y() const {
    return GetField<int32_t>(VT_Y, 0);
  }
  int32_t z() const {
    return GetField<int32_t>(VT_Z, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_X, 4) &&
           VerifyField<int32_t>(verifier, VT_Y, 4) &&
           VerifyField<int32_t>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
};

struct MovementPacketBuilder {
  typedef MovementPacket Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_x(int32_t x) {
    fbb_.AddElement<int32_t>(MovementPacket::VT_X, x, 0);
  }
  void add_y(int32_t y) {
    fbb_.AddElement<int32_t>(MovementPacket::VT_Y, y, 0);
  }
  void add_z(int32_t z) {
    fbb_.AddElement<int32_t>(MovementPacket::VT_Z, z, 0);
  }
  explicit MovementPacketBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<MovementPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MovementPacket>(end);
    return o;
  }
};

inline flatbuffers::Offset<MovementPacket> CreateMovementPacket(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t x = 0,
    int32_t y = 0,
    int32_t z = 0) {
  MovementPacketBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

}  // namespace Movement
}  // namespace MProject

#endif  // FLATBUFFERS_GENERATED_MOVEMENT_MPROJECT_MOVEMENT_H_
